spring:
    lifecycle:
        timeout-per-shutdown-phase: ${PRODUCT_SERVICE_SHUTDOWN_TIMEOUT:${GRACEFUL_SHUTDOWN_TIMEOUT:30s}}
    profiles:
        default: local
    security:
        user:
            name: ${PRODUCT_SERVICE_USERNAME}
            password: ${PRODUCT_SERVICE_PASSWORD}

server:
    shutdown: graceful

app:
    data:
        migrations:
            enabled: ${APP_DATA_MIGRATIONS_ENABLED:true}
            fail-fast: ${APP_DATA_MIGRATIONS_FAIL_FAST:true}
        seed:
            enabled: ${APP_DATA_SEED_ENABLED:false}
            products-path: ${PRODUCT_SAMPLE_DATA_PATH:../../static/sample-data/structured-data/product-service.products.json}
    security:
        internal-service-token: ${INTERNAL_SERVICE_TOKEN:AYmtWAAxsNTXoHtWZYjyQ1k01u8huw9fIIo1VAkbA3t}

logging:
    level:
        com.netflix.discovery.TimedSupervisorTask: ERROR
