{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.defaultSecretName }}
  labels:
{{ include "modern-ecommerce.labels" . | indent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName | quote }}
    kind: {{ .Values.externalSecrets.secretStoreKind | quote }}
  target:
    name: {{ .Values.secrets.defaultSecretName }}
    creationPolicy: Owner
  data:
{{- $secretKeys := dict }}
{{- range $name, $workload := .Values.workloads }}
{{- range $key := $workload.secretEnv }}
{{- if not (hasKey $secretKeys $key) }}
{{- $_ := set $secretKeys $key true }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ printf "%s/%s" $.Values.externalSecrets.secretNamePrefix (lower (replace "_" "-" $key)) | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
